config/routes.rb
Rails.application.routes.draw do
  resources :lengths

  resources :colors

  resources :dress_types

  resources :brands

  resources :dresses

  match "/load_content" => "dresses#load_content", via: :post

end

app/models/length.rb
class Length < ActiveRecord::Base
  belongs_to :dress
end

app/controllers/lengths_controller.rb
class LengthsController < ApplicationController
  before_action :set_length, only: [:show, :edit, :update, :destroy]

  # GET /lengths
  # GET /lengths.json
  def index
    @lengths = Length.all
  end

  # GET /lengths/1
  # GET /lengths/1.json
  def show
  end

  # GET /lengths/new
  def new
    @length = Length.new
  end

  # GET /lengths/1/edit
  def edit
  end

  # POST /lengths
  # POST /lengths.json
  def create
    @length = Length.new(length_params)

    respond_to do |format|
      if @length.save
        format.html { redirect_to @length, notice: 'Length was successfully created.' }
        format.json { render :show, status: :created, location: @length }
      else
        format.html { render :new }
        format.json { render json: @length.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lengths/1
  # PATCH/PUT /lengths/1.json
  def update
    respond_to do |format|
      if @length.update(length_params)
        format.html { redirect_to @length, notice: 'Length was successfully updated.' }
        format.json { render :show, status: :ok, location: @length }
      else
        format.html { render :edit }
        format.json { render json: @length.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lengths/1
  # DELETE /lengths/1.json
  def destroy
    @length.destroy
    respond_to do |format|
      format.html { redirect_to lengths_url, notice: 'Length was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_length
      @length = Length.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def length_params
      params.require(:length).permit(:name, :dress_id)
    end
end

app/helpers/lengths_helper.rb
module LengthsHelper
end

app/views/lengths/_form.html.erb
<%= form_for(@length) do |f| %>
  <% if @length.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@length.errors.count, "error") %> prohibited this length from being saved:</h2>

      <ul>
      <% @length.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dress_id %><br>
    <%= f.text_field :dress_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lengths/edit.html.erb
<h1>Editing length</h1>

<%= render 'form' %>

<%= link_to 'Show', @length %> |
<%= link_to 'Back', lengths_path %>

app/views/lengths/index.html.erb
<h1>Listing lengths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lengths.each do |length| %>
      <tr>
        <td><%= length.name %></td>
        <td><%= length.dress %></td>
        <td><%= link_to 'Show', length %></td>
        <td><%= link_to 'Edit', edit_length_path(length) %></td>
        <td><%= link_to 'Destroy', length, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Length', new_length_path %>

app/views/lengths/new.html.erb
<h1>New length</h1>

<%= render 'form' %>

<%= link_to 'Back', lengths_path %>

app/views/lengths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @length.name %>
</p>

<p>
  <strong>Dress:</strong>
  <%= @length.dress %>
</p>

<%= link_to 'Edit', edit_length_path(@length) %> |
<%= link_to 'Back', lengths_path %>