config/routes.rb
Rails.application.routes.draw do
  resources :lengths

  resources :colors

  resources :dress_types

  resources :brands

  resources :dresses

  match "/load_content" => "dresses#load_content", via: :post

end

app/controllers/dress_types_controller.rb
class DressTypesController < ApplicationController
  before_action :set_dress_type, only: [:show, :edit, :update, :destroy]

  # GET /dress_types
  # GET /dress_types.json
  def index
    @dress_types = DressType.all
  end

  # GET /dress_types/1
  # GET /dress_types/1.json
  def show
  end

  # GET /dress_types/new
  def new
    @dress_type = DressType.new
  end

  # GET /dress_types/1/edit
  def edit
  end

  # POST /dress_types
  # POST /dress_types.json
  def create
    @dress_type = DressType.new(dress_type_params)

    respond_to do |format|
      if @dress_type.save
        format.html { redirect_to @dress_type, notice: 'Dress type was successfully created.' }
        format.json { render :show, status: :created, location: @dress_type }
      else
        format.html { render :new }
        format.json { render json: @dress_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dress_types/1
  # PATCH/PUT /dress_types/1.json
  def update
    respond_to do |format|
      if @dress_type.update(dress_type_params)
        format.html { redirect_to @dress_type, notice: 'Dress type was successfully updated.' }
        format.json { render :show, status: :ok, location: @dress_type }
      else
        format.html { render :edit }
        format.json { render json: @dress_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dress_types/1
  # DELETE /dress_types/1.json
  def destroy
    @dress_type.destroy
    respond_to do |format|
      format.html { redirect_to dress_types_url, notice: 'Dress type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dress_type
      @dress_type = DressType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dress_type_params
      params.require(:dress_type).permit(:name, :dress_id)
    end
end

app/helpers/dress_types_helper.rb
module DressTypesHelper
end

app/views/dress_types/_form.html.erb
<%= form_for(@dress_type) do |f| %>
  <% if @dress_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dress_type.errors.count, "error") %> prohibited this dress_type from being saved:</h2>

      <ul>
      <% @dress_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dress_id %><br>
    <%= f.text_field :dress_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dress_types/edit.html.erb
<h1>Editing dress_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @dress_type %> |
<%= link_to 'Back', dress_types_path %>

app/views/dress_types/index.html.erb
<h1>Listing dress_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dress_types.each do |dress_type| %>
      <tr>
        <td><%= dress_type.name %></td>
        <td><%= dress_type.dress %></td>
        <td><%= link_to 'Show', dress_type %></td>
        <td><%= link_to 'Edit', edit_dress_type_path(dress_type) %></td>
        <td><%= link_to 'Destroy', dress_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dress type', new_dress_type_path %>

app/views/dress_types/new.html.erb
<h1>New dress_type</h1>

<%= render 'form' %>

<%= link_to 'Back', dress_types_path %>

app/views/dress_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dress_type.name %>
</p>

<p>
  <strong>Dress:</strong>
  <%= @dress_type.dress %>
</p>

<%= link_to 'Edit', edit_dress_type_path(@dress_type) %> |
<%= link_to 'Back', dress_types_path %>